import assert from 'node:assert/strict';
import { test } from 'node:test';
import { parseDates } from './dates.ts';
// Generated by running the C# bot's DateParseExtensions.ParseDates over each input
import table from './testdata/dates.json' with { type: 'json' };

for (const { input, dates } of table) {
  test(`parseDates(${JSON.stringify(input)})`, () => {
    assert.deepEqual(parseDates(input), dates);
  });
}
