import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test, type TestContext } from 'node:test';
import { buildReply } from './format.ts';
import { getSetlists } from './setlists.ts';

// The testdata/*.md replies were generated by running the C# bot on the same input
const expected = (name: string) =>
  readFileSync(new URL(`./testdata/${name}`, import.meta.url), 'utf8');

/** Serves a C# test fixture for every fetch, and records the requested URLs. */
function mockFetch(t: TestContext, fixture: string) {
  const urls: string[] = [];
  const body = readFileSync(new URL(`../../test/${fixture}`, import.meta.url));
  t.mock.method(globalThis, 'fetch', async (url: string) => {
    urls.push(url);
    return new Response(body);
  });
  return urls;
}

test('phish', async (t) => {
  const urls = mockFetch(
    t,
    'Setlistbot.Infrastructure.PhishNet/PhishNetResponses/1997-11-22-setlist-response.json'
  );

  const setlists = await getSetlists('phish', ['1997-11-22'], {
    phishNetApiKey: 'MyApiKey',
  });

  assert.deepEqual(urls, [
    'https://api.phish.net/v5/setlists/showdate/1997-11-22.json?apikey=MyApiKey',
  ]);
  assert.equal(buildReply(setlists), expected('phish-single.md'));
  assert.equal(
    buildReply([...setlists, ...setlists]),
    expected('phish-multi.md')
  );
});

test('kglw', async (t) => {
  const urls = mockFetch(
    t,
    'Setlistbot.Infrastructure.KglwNet.UnitTests/KglwNetResponses/2022-10-10-setlist-response.json'
  );

  const setlists = await getSetlists('kglw', ['2022-10-10']);

  assert.deepEqual(urls, [
    'https://kglw.net/api/v2/setlists/showdate/2022-10-10.json',
  ]);
  assert.equal(buildReply(setlists), expected('kglw-single.md'));
  assert.equal(
    buildReply([...setlists, ...setlists]),
    expected('kglw-multi.md')
  );
});

for (const date of [
  '1977-05-08',
  '1972-04-07',
  '1990-03-21',
  '1968-02-22',
  '1967-11-14',
]) {
  test(`gd ${date}`, async () => {
    assert.equal(
      buildReply(await getSetlists('gd', [date])),
      expected(`gd-${date}.md`)
    );
  });
}

test('gd several dates', async () => {
  const setlists = await getSetlists('gd', [
    '1972-04-07',
    '1970-07-03',
    '1977-05-08',
  ]);
  assert.equal(buildReply(setlists), expected('gd-multi.md'));
});

for (const date of ['1969-02-04', '1969-04-15']) {
  test(`gd ${date} is in Omaha, NE, USA`, async () => {
    const [setlist] = await getSetlists('gd', [date]);
    assert.equal(setlist?.location, 'The Music Box, Omaha, NE, USA');
  });
}

test('no setlists means no reply', async () => {
  assert.equal(buildReply(await getSetlists('gd', ['1999-01-01'])), '');
  assert.equal(buildReply([]), '');
});

test('a failed request doesn’t leak the API key', async (t) => {
  t.mock.method(
    globalThis,
    'fetch',
    async () => new Response('', { status: 500 })
  );
  await assert.rejects(
    getSetlists('phish', ['1997-11-22'], { phishNetApiKey: 'MyApiKey' }),
    (error: Error) => {
      assert.equal(error.message, 'api.phish.net returned 500');
      return true;
    }
  );
});

const phishResponse = (envelope: object) => async () =>
  new Response(JSON.stringify({ data: [], ...envelope }));

test('a phish.net error in an HTTP 200 body throws', async (t) => {
  t.mock.method(
    globalThis,
    'fetch',
    phishResponse({ error: 2, error_message: 'Invalid API key' })
  );
  await assert.rejects(
    getSetlists('phish', ['1997-11-22'], { phishNetApiKey: 'MyApiKey' }),
    {
      message: 'phish.net error: Invalid API key',
    }
  );
});

for (const error of [false, 11]) {
  test(`a phish.net date with no show (error ${error}) has no setlists`, async (t) => {
    t.mock.method(globalThis, 'fetch', phishResponse({ error }));
    assert.deepEqual(
      await getSetlists('phish', ['1997-11-22'], {
        phishNetApiKey: 'MyApiKey',
      }),
      []
    );
  });
}
