version: 2

updates:
  # Enable vesion updates for NuGet packages
  - package-ecosystem: "nuget"
    # Location of NuGet packages
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Customize the commit message prefix
      prefix: "chore(deps): "
    # Limit the number of open pull requests created by Dependabot
    open-pull-requests-limit: 1
    # group all nuget dependencies to be updated together
    groups:
      dotnet-dependencies:
        patterns:
          - "*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      # Customize the commit message prefix
      prefix: "chore(deps): "
    # Limit the number of open pull requests created by Dependabot
    open-pull-requests-limit: 1
    # group all github actions dependencies to be updated together
    groups:
      github-actions:
        patterns:
          - "*"