@startuml C2 Containers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(discordUser, "Discord User", "User /setlist command.")
Person(redditUser, "Reddit User", "Uses Reddit to comment/post.")

System_Boundary(setlistbot, "Setlistbot System") {
    Container(bot, "Setlistbot", "dotnet", "Reddit/Discord bot", $sprite="robot")
    ContainerDb(db, "Database", "Azure Table Storage", "Stores show data and comments")
}

System_Ext(reddit, "Reddit", "Social media platform")
System_Ext(discord, "Discord", "Social media platform")
System_Ext(songfish, "Songfish", "Show database")
System_Ext(phishnet, "Phish.net", "Show database")

Rel(redditUser, reddit, "Uses")
Rel(discordUser, discord, "Uses")
Rel(bot, reddit, "Replies to comments")
Rel(discord, bot, "Sends interaction requests")
Rel(bot, db, "Reads/writes show data")
Rel(bot, songfish, "Queries for show data")
Rel(bot, phishnet, "Queries for show data")

LAYOUT_WITH_LEGEND()

@enduml