
@startuml C1 System Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(discordUser, "Discord User", "Issues bot command.")
Person(redditUser, "Reddit User", "Uses Reddit to comment/post.")

System(setlistbotSystem, "Setlistbot", $sprite="robot")
System_Ext(reddit, "Reddit")
System_Ext(discord, "Discord")
System_Ext(songfish, "Songfish")
System_Ext(phishnet, "Phish.net")

Rel(redditUser, reddit, "Makes a comment")
Rel(discordUser, discord, "Uses /setlist command")
Rel(setlistbotSystem, reddit, "Responds to comments")
Rel(discord, setlistbotSystem, "Sends interactions")
Rel(setlistbotSystem, songfish, "Retrieves setlists")
Rel(setlistbotSystem, phishnet, "Retrieves setlists")

LAYOUT_WITH_LEGEND()
@enduml