name: Deploy setlistbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Release Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --no-build --configuration Release --output ./publish

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: setlistbot
          path: ./publish
          if-no-files-found: error

  deploy_test:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: Test

    env:
      ENV_NAME: test
      ARTIST_ID: kglw
      RG_NAME: rg-setlistbot-test
      FUNC_NAME: func-setlistbot-kglw-test

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: setlistbot
          path: ./publish

      - name: Deploy Setlistbot to Test Environment
        uses: Azure/functions-action@v1
        with:
          app-name: $FUNC_NAME
          package: "./publish"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNC_SETLISTBOT_KGLW_TEST }}
