name: Deploy setlistbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore Tools
        run: dotnet tool restore

      - name: Verify Formatting
        run: dotnet format --verify-no-changes

      - name: Run CSharpier
        run: dotnet csharpier check .

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Release Build Reddit Bot
        run: dotnet build src/Setlistbot.Function.RedditBot/Setlistbot.Function.RedditBot.csproj --configuration Release --output ./RedditBot

      - name: Release Build Discord Bot
        run: dotnet build src/Setlistbot.Function.Discord/Setlistbot.Function.Discord.csproj --configuration Release --output ./DiscordBot

      - name: Upload Reddit Bot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: redditbot
          path: ./RedditBot
          if-no-files-found: error
          include-hidden-files: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: discordbot
          path: ./DiscordBot
          if-no-files-found: error
          include-hidden-files: true

  deploy_reddit_kglw_test:
    name: "Deploy Reddit Bot (KGLW) to Test Environment"
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: Test

    steps:
      - uses: actions/checkout@v5

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: redditbot
          path: ./RedditBot

      - name: Deploy Reddit Bot to Test Environment
        uses: Azure/functions-action@v1
        with:
          app-name: func-setlistbot-reddit-kglw-test
          package: "./RedditBot"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNC_SETLISTBOT_KGLW_TEST }}

  deploy_reddit_phish_test:
    name: "Deploy Reddit Bot (Phish) to Test Environment"
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: Test

    steps:
      - uses: actions/checkout@v5

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: redditbot
          path: ./RedditBot

      - name: Deploy Reddit Bot to Test Environment
        uses: Azure/functions-action@v1
        with:
          app-name: func-setlistbot-reddit-phish-test
          package: "./RedditBot"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNC_SETLISTBOT_PHISH_TEST }}

  deploy_reddit_gd_test:
    name: "Deploy Reddit Bot (Grateful Dead) to Test Environment"
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: Test

    steps:
      - uses: actions/checkout@v5

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: redditbot
          path: ./RedditBot

      - name: Deploy Reddit Bot to Test Environment
        uses: Azure/functions-action@v1
        with:
          app-name: func-setlistbot-reddit-gd-test
          package: "./RedditBot"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNC_SETLISTBOT_GD_TEST }}

  deploy_discord_test:
    name: "Deploy Discord Bot to Test Environment"
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: Test

    steps:
      - uses: actions/checkout@v5

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: discordbot
          path: ./DiscordBot

      - name: Deploy Discord Bot to Test Environment
        uses: Azure/functions-action@v1
        with:
          app-name: func-setlistbot-discord-test
          package: "./DiscordBot"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNC_DISCORDBOT_TEST }}

  deploy_reddit_kglw_prod:
    name: "Deploy Reddit Bot (KGLW) to Prod Environment"
    needs: deploy_reddit_kglw_test
    runs-on: ubuntu-latest

    environment:
      name: Prod

    steps:
      - uses: actions/checkout@v5

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: redditbot
          path: ./RedditBot

      - name: Deploy Reddit Bot to Prod Environment
        uses: Azure/functions-action@v1
        with:
          app-name: func-setlistbot-reddit-kglw-prod
          package: "./RedditBot"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNC_SETLISTBOT_KGLW_PROD }}

  deploy_reddit_phish_prod:
    name: "Deploy Reddit Bot (Phish) to Prod Environment"
    needs: deploy_reddit_phish_test
    runs-on: ubuntu-latest

    environment:
      name: Prod

    steps:
      - uses: actions/checkout@v5

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: redditbot
          path: ./RedditBot

      - name: Deploy Reddit Bot to Prod Environment
        uses: Azure/functions-action@v1
        with:
          app-name: func-setlistbot-reddit-phish-prod
          package: "./RedditBot"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNC_SETLISTBOT_PHISH_PROD }}

  deploy_reddit_gd_prod:
    name: "Deploy Reddit Bot (Grateful Dead) to Prod Environment"
    needs: deploy_reddit_gd_test
    runs-on: ubuntu-latest

    environment:
      name: Prod

    steps:
      - uses: actions/checkout@v5

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: redditbot
          path: ./RedditBot

      - name: Deploy Reddit Bot to Prod Environment
        uses: Azure/functions-action@v1
        with:
          app-name: func-setlistbot-reddit-gd-prod
          package: "./RedditBot"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNC_SETLISTBOT_GD_PROD }}

  deploy_discord_prod:
    name: "Deploy Discord Bot to Prod Environment"
    needs: deploy_discord_test
    runs-on: ubuntu-latest

    environment:
      name: Prod

    steps:
      - uses: actions/checkout@v5

      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: discordbot
          path: ./DiscordBot

      - name: Deploy Discord Bot to Prod Environment
        uses: Azure/functions-action@v1
        with:
          app-name: func-setlistbot-discord-prod
          package: "./DiscordBot"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNC_DISCORDBOT_PROD }}
