name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  deploy_reddit_kglw_prod:
    name: "Deploy Reddit Bot (KGLW) to Prod Environment"
    runs-on: ubuntu-latest

    environment:
      name: Prod

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Release Build Reddit Bot
        run: dotnet build src/Setlistbot.Function.RedditBot/Setlistbot.Function.RedditBot.csproj --configuration Release --output ./RedditBot

      - name: Deploy Reddit Bot to Prod Environment
        uses: Azure/functions-action@v1
        with:
          app-name: func-setlistbot-reddit-kglw-prod
          package: "./RedditBot"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNC_SETLISTBOT_KGLW_PROD }}

  deploy_reddit_phish_prod:
    name: "Deploy Reddit Bot (Phish) to Prod Environment"
    runs-on: ubuntu-latest

    environment:
      name: Prod

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Release Build Reddit Bot
        run: dotnet build src/Setlistbot.Function.RedditBot/Setlistbot.Function.RedditBot.csproj --configuration Release --output ./RedditBot

      - name: Deploy Reddit Bot to Prod Environment
        uses: Azure/functions-action@v1
        with:
          app-name: func-setlistbot-reddit-phish-prod
          package: "./RedditBot"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNC_SETLISTBOT_PHISH_PROD }}

  deploy_reddit_gd_prod:
    name: "Deploy Reddit Bot (Grateful Dead) to Prod Environment"
    runs-on: ubuntu-latest

    environment:
      name: Prod

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Release Build Reddit Bot
        run: dotnet build src/Setlistbot.Function.RedditBot/Setlistbot.Function.RedditBot.csproj --configuration Release --output ./RedditBot

      - name: Deploy Reddit Bot to Prod Environment
        uses: Azure/functions-action@v1
        with:
          app-name: func-setlistbot-reddit-gd-prod
          package: "./RedditBot"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNC_SETLISTBOT_GD_PROD }}

  deploy_discord_prod:
    name: "Deploy Discord Bot to Prod Environment"
    runs-on: ubuntu-latest

    environment:
      name: Prod

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Release Build Discord Bot
        run: dotnet build src/Setlistbot.Function.Discord/Setlistbot.Function.Discord.csproj --configuration Release --output ./DiscordBot

      - name: Deploy Discord Bot to Prod Environment
        uses: Azure/functions-action@v1
        with:
          app-name: func-setlistbot-discord-prod
          package: "./DiscordBot"
          publish-profile: ${{ secrets.PUBLISH_PROFILE_FUNC_DISCORDBOT_PROD }}