name: setlistbot PR Verification

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore Tools
        run: dotnet tool restore

      - name: Run CSharpier
        run: dotnet csharpier check .

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  devvit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devvit

    steps:
      - uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: devvit/.nvmrc
          cache: npm
          cache-dependency-path: devvit/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Check Formatting
        run: npm run test:format

      - name: Typecheck
        run: npm run test:types

      - name: Lint
        run: npm run test:lint

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
